# Only used for testing the docker images
version: '3'
services:
  elassandra-1:
    image: elassandra:test
    environment:
       - CASSANDRA_CLUSTER_NAME=elassandra
       - CASSANDRA_SEEDS=elassandra-1
       - MAX_HEAP_SIZE=512m
       - HEAP_NEWSIZE=128m
       - JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/logs/1:/usr/share/elassandra/logs
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elassandra-2:
    image: elassandra:test
    environment:
       - CASSANDRA_CLUSTER_NAME=elassandra
       - CASSANDRA_SEEDS=elassandra-1
       - MAX_HEAP_SIZE=512m
       - HEAP_NEWSIZE=128m
       - JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/logs/2:/usr/share/elassandra/logs
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
