#!/usr/bin/env bash
# Elasticsearch fork ClusterService#createOrUpdateElasticAdminKeyspace() — OpenSearch side-car stubs omitted it;
# Node.start() post-discovery hook requires this for elastic_admin / tests. Idempotent.
#
# Usage: ./scripts/patch-opensearch-cluster-service-create-elastic-admin-keyspace.sh "${OPENSEARCH_CLONE_DIR}"
set -euo pipefail
DEST="${1:?OpenSearch clone root}"
CS="$DEST/server/src/main/java/org/opensearch/cluster/service/ClusterService.java"
[[ -f "$CS" ]] || exit 0

if grep -q "createOrUpdateElasticAdminKeyspace" "$CS" 2>/dev/null; then
  echo "ClusterService already has createOrUpdateElasticAdminKeyspace → $CS"
  exit 0
fi

python3 - "$CS" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
anchor = (
    "    public boolean hasMetaDataTable() {\n"
    "        org.apache.cassandra.schema.KeyspaceMetadata ksm = org.apache.cassandra.schema.Schema.instance.getKeyspaceMetadata(getElasticAdminKeyspaceName());\n"
    "        return ksm != null && ksm.getTableOrViewNullable(ELASTIC_ADMIN_METADATA_TABLE) != null;\n"
    "    }\n\n"
    "    /** Block until local shards are started (CassandraShardStartedBarrier). */\n"
    "    public void blockUntilShardsStarted() {"
)
if anchor not in text:
    print("patch: hasMetaDataTable / blockUntilShardsStarted anchor not found", path, file=sys.stderr)
    sys.exit(1)
insert = (
    "    public boolean hasMetaDataTable() {\n"
    "        org.apache.cassandra.schema.KeyspaceMetadata ksm = org.apache.cassandra.schema.Schema.instance.getKeyspaceMetadata(getElasticAdminKeyspaceName());\n"
    "        return ksm != null && ksm.getTableOrViewNullable(ELASTIC_ADMIN_METADATA_TABLE) != null;\n"
    "    }\n\n"
    "    /**\n"
    "     * Create or update elastic_admin keyspace and metadata_log (Elasticsearch fork {@code ClusterService} parity).\n"
    "     */\n"
    "    public void createOrUpdateElasticAdminKeyspace() {\n"
    "        final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(ClusterService.class);\n"
    "        final String ks = getElasticAdminKeyspaceName();\n"
    "        final int maxAttempts = Integer.getInteger(\"elassandra.create_elastic_admin_retry.attempts\", 5);\n"
    "        org.apache.cassandra.cql3.UntypedResultSet result = org.apache.cassandra.cql3.QueryProcessor.executeOnceInternal(\n"
    "            String.format(java.util.Locale.ROOT, \"SELECT replication FROM system_schema.keyspaces WHERE keyspace_name='%s'\", ks));\n"
    "        if (result.isEmpty()) {\n"
    "            for (int i = 0; ; i++) {\n"
    "                try {\n"
    "                    java.util.Map<String, String> replication = new java.util.HashMap<>();\n"
    "                    replication.put(\"class\", org.apache.cassandra.locator.NetworkTopologyStrategy.class.getName());\n"
    "                    replication.put(org.apache.cassandra.config.DatabaseDescriptor.getLocalDataCenter(), \"1\");\n"
    "                    String createKeyspace = String.format(\n"
    "                        java.util.Locale.ROOT,\n"
    "                        \"CREATE KEYSPACE IF NOT EXISTS \\\"%s\\\" WITH replication = %s;\",\n"
    "                        ks,\n"
    "                        org.apache.cassandra.utils.FBUtilities.json(replication).replaceAll(\"\\\"\", \"'\")\n"
    "                    );\n"
    "                    process(\n"
    "                        org.apache.cassandra.db.ConsistencyLevel.LOCAL_ONE,\n"
    "                        org.apache.cassandra.service.ClientState.forInternalCalls(),\n"
    "                        createKeyspace\n"
    "                    );\n"
    "                    break;\n"
    "                } catch (Exception e) {\n"
    "                    if (i >= maxAttempts) {\n"
    "                        log.error(\"Failed to create elastic_admin keyspace after {} attempts\", maxAttempts, e);\n"
    "                        return;\n"
    "                    }\n"
    "                    log.info(\"Retrying create elastic_admin keyspace\");\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            java.util.Map<String, String> replication = result.one().getFrozenTextMap(\"replication\");\n"
    "            log.debug(\"keyspace={} replication={}\", ks, replication);\n"
    "            if (!org.apache.cassandra.locator.NetworkTopologyStrategy.class.getName().equals(replication.get(\"class\"))) {\n"
    "                throw new org.apache.cassandra.exceptions.ConfigurationException(\n"
    "                    \"Keyspace [\" + ks + \"] should use \" + org.apache.cassandra.locator.NetworkTopologyStrategy.class.getName()\n"
    "                );\n"
    "            }\n"
    "        }\n"
    "        result = org.apache.cassandra.cql3.QueryProcessor.executeOnceInternal(\n"
    "            String.format(\n"
    "                java.util.Locale.ROOT,\n"
    "                \"SELECT * FROM system_schema.tables WHERE keyspace_name='%s' AND table_name = '%s'\",\n"
    "                ks,\n"
    "                ELASTIC_ADMIN_METADATA_TABLE\n"
    "            )\n"
    "        );\n"
    "        if (result.isEmpty()) {\n"
    "            for (int i = 0; ; i++) {\n"
    "                try {\n"
    "                    String createTable = String.format(\n"
    "                        java.util.Locale.ROOT,\n"
    "                        \"CREATE TABLE IF NOT EXISTS \\\"%s\\\".%s ( \"\n"
    "                            + \"    cluster_name text,\"\n"
    "                            + \"    v bigint,\"\n"
    "                            + \"    owner uuid,\"\n"
    "                            + \"    source text,\"\n"
    "                            + \"    ts timestamp,\"\n"
    "                            + \"    version bigint static,\"\n"
    "                            + \"    PRIMARY KEY (cluster_name, v)\"\n"
    "                            + \") WITH CLUSTERING ORDER BY (v DESC);\",\n"
    "                        ks,\n"
    "                        ELASTIC_ADMIN_METADATA_TABLE\n"
    "                    );\n"
    "                    process(\n"
    "                        org.apache.cassandra.db.ConsistencyLevel.LOCAL_ONE,\n"
    "                        org.apache.cassandra.service.ClientState.forInternalCalls(),\n"
    "                        createTable\n"
    "                    );\n"
    "                    org.opensearch.cluster.metadata.Metadata metadata = state().metadata();\n"
    "                    String source = String.format(\n"
    "                        java.util.Locale.ROOT, \"init table %s.%s\", ks, ELASTIC_ADMIN_METADATA_TABLE);\n"
    "                    String initQ = String.format(\n"
    "                        java.util.Locale.ROOT,\n"
    "                        \"UPDATE \\\"%s\\\".\\\"%s\\\" SET owner = ?, version = ?, source= ?, ts = dateOf(now()) \"\n"
    "                            + \"WHERE cluster_name = ? AND v = ? IF version = null\",\n"
    "                        ks,\n"
    "                        ELASTIC_ADMIN_METADATA_TABLE\n"
    "                    );\n"
    "                    process(\n"
    "                        org.apache.cassandra.db.ConsistencyLevel.LOCAL_ONE,\n"
    "                        org.apache.cassandra.service.ClientState.forInternalCalls(),\n"
    "                        initQ,\n"
    "                        java.util.UUID.fromString(org.apache.cassandra.service.StorageService.instance.getLocalHostId()),\n"
    "                        metadata.version(),\n"
    "                        source,\n"
    "                        org.apache.cassandra.config.DatabaseDescriptor.getClusterName(),\n"
    "                        metadata.version()\n"
    "                    );\n"
    "                    break;\n"
    "                } catch (Exception e) {\n"
    "                    if (i >= maxAttempts) {\n"
    "                        log.error(\n"
    "                            new org.apache.logging.log4j.message.ParameterizedMessage(\n"
    "                                \"Failed to create or init table {}.{}\", ks, ELASTIC_ADMIN_METADATA_TABLE\n"
    "                            ),\n"
    "                            e\n"
    "                        );\n"
    "                        return;\n"
    "                    }\n"
    "                    log.info(\"Retrying create elastic_admin metadata table\");\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n\n"
    "    /** Block until local shards are started (CassandraShardStartedBarrier). */\n"
    "    public void blockUntilShardsStarted() {"
)
text = text.replace(anchor, insert, 1)
path.write_text(text, encoding="utf-8")
print("Patched ClusterService#createOrUpdateElasticAdminKeyspace →", path)
PY
