version: '2.4'
services:
  seed_node:
    image: "elassandra:test"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "DEBUG=true"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
    ports:
      - "9042:9042"
      - "9200:9200"
  node:
    image: "elassandra:test"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_SEEDS=seed_node"
      - "DEBUG=true"
    links:
      - seed_node
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
  dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.20
    environment:
      - 'OPENSEARCH_HOSTS=["http://seed_node:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - "5601:5601"
    mem_limit: 500m